info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  levels:
    root: debug
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG